name: Deprovision

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      REMOTE_ECHIDNA_S3_BUCKET:
        required: true


jobs:
  deprovision:
    name: Deprovision old jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone remote-echidna
        run: git submodule add https://github.com/aviggiano/remote-echidna.git
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Deprovision old jobs
        working-directory: ./remote-echidna
        run: ./scripts/deprovision.sh ${{ secrets.REMOTE_ECHIDNA_S3_BUCKET }}
