name: Remote Echidna

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      project_git_url:
        required: true
        type: string
      project_git_checkout:
        required: true
        type: string
      run_tests_cmd:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      REMOTE_ECHIDNA_S3_BUCKET:
        required: true
      REMOTE_ECHIDNA_EC2_INSTANCE_KEY_NAME:
        required: true


jobs:
  deprovision:
    name: Deprovision old resources
    uses: ./.github/workflows/deprovision.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REMOTE_ECHIDNA_S3_BUCKET: ${{ secrets.REMOTE_ECHIDNA_S3_BUCKET }}
  provision:
    name: Provision new resources
    uses: ./.github/workflows/provision.yml
    with:
      project: ${{ inputs.project }}
      project_git_url: ${{ inputs.project_git_url }}
      project_git_checkout: ${{ inputs.project_git_checkout }}
      run_tests_cmd: ${{ inputs.run_tests_cmd }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REMOTE_ECHIDNA_S3_BUCKET: ${{ secrets.REMOTE_ECHIDNA_S3_BUCKET }}
      REMOTE_ECHIDNA_EC2_INSTANCE_KEY_NAME: ${{ secrets.REMOTE_ECHIDNA_EC2_INSTANCE_KEY_NAME }}